[".config/git-delta/themes.gitconfig"]
    type = "file"
    url = "https://raw.githubusercontent.com/dandavison/delta/main/themes.gitconfig"
    refreshPeriod = "168h"

[".config/fzf/tokyonight_night.sh"]
    type = "file"
    url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/fzf/tokyonight_night.sh"
    refreshPeriod = "168h"

