alias ggpushf="ggpush --force-with-lease"
alias brewup="brew update; brew upgrade; brew cleanup; brew doctor"
alias {ZSHRC, zshrc}="$EDITOR ~/.zshrc"
alias .df="git --git-dir=$HOME/.dotfiles/.git --work-tree=$HOME/.dotfiles"
alias .dfl="git --git-dir=$HOME/.dotfiles_local/.git --work-tree=$HOME/.dotfiles_local"