tap "homebrew/bundle"
tap "homebrew/cask-fonts"
brew 'mas' # Mac App Store manager
cask 'todoist'
brew 'git-delta'
brew 'bat'
brew 'tmuxinator'
brew 'chezmoi'
brew 'starship'
brew 'minikube'
brew 'docker-compose'
brew 'docker'
brew 'urlview'
brew 'gh'
brew 'tldr'
brew 'reattach-to-user-namespace'
brew 'fpp'
brew 'the_silver_searcher'
cask 'bitwarden'
cask 'dropbox'
cask 'alacritty'
cask 'alfred'
cask 'rectangle'
cask 'font-fira-code'
brew 'zsh'
brew 'neovim'
cask 'spotify'
cask 'visual-studio-code'
brew 'autojump'
brew 'asdf'
brew 'tmux'
brew 'jq'
brew 'curl'
brew 'git'
brew 'unzip'
brew 'unixodbc'
brew 'libtool'
brew 'libxslt'
brew 'readline'
brew 'libyaml'
brew 'openssl'
cask 'obsidian'
brew 'autoconf'
brew 'automake'
brew 'gpg'
brew 'coreutils'
vscode "eamodio.gitlens"
vscode "github.codespaces"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.github-vscode-theme"
vscode "github.vscode-github-actions"
vscode "golang.go"
vscode "hashicorp.terraform"
vscode "kaiwood.endwise"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vsliveshare.vsliveshare"
vscode "ms-vsliveshare.vsliveshare-pack"
vscode "redhat.vscode-yaml"
vscode "shopify.ruby-lsp"
vscode "sissel.shopify-liquid"
vscode "vscodevim.vim"
vscode "will-wow.vscode-alternate-file"
vscode "editorconfig.editorconfig"
