tap 'homebrew/cask'
tap 'homebrew/cask-fonts'

# Core dependencies for Apps
brew 'coreutils'
brew 'gpg'
brew 'automake'
brew 'autoconf'
brew 'openssl'
brew 'libyaml'
brew 'readline'
brew 'libxslt'
brew 'libtool'
brew 'unixodbc'
brew 'unzip'
brew 'curl'

# Apps / Simple Binaries
brew 'asdf'
brew 'autojump'
cask 'visual-studio-code'
cask 'whatsapp'
cask 'spotify'
cask 'slack'
brew 'vim'
cask 'flux'
cask 'docker'
cask 'hyper'
brew 'zsh'
brew 'zsh-completions'
cask 'google-chrome'
cask 'font-fira-code'
cask 'discord'
