alias ggpushf="ggpush --force-with-lease"
alias brewup="brew update; brew upgrade; brew cleanup; brew doctor"
alias {ZSHRC, zshrc}="$EDITOR ~/.zshrc"
alias cat="bat --paging=never"
alias catp="bat"
alias vim="nvim"
alias cz=chezmoi
alias ghcs="gh copilot suggest"
alias ghce="gh copilot explain"
alias tf="terraform"
alias htop="btop"
alias top="htop"
