import = ["~/.config/alacritty/themes/themes/dracula_plus.toml"]

[font]
  [font.normal]
  family = "Fira Code"
  style = "Regular"

  [font.bold]
  family = "Fira Code"
  style = "Bold"

  [font.italic]
  family = "Fira Code"
  style = "Italic"

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]
